### ISSUE TITLE
How to get files in /public/src folder?

### ISSUE THREAD

**Issue by gunnrcrakr** [moikzz214/Codeigniter4_vue_vuetify_webpack_installation#1]

**Comment by moikzz214** [comment]
It's not on the public folder, you need to create on root folder
/
/public
/src

**Comment by gunnrcrakr** [comment]
I mean this.

https://i.imgur.com/vDzYzQC.png

**Comment by moikzz214** [comment]
> _No description provided._

It's not on the public folder, you need to create on root folder
/
/public
/src

**Comment by moikzz214** [comment]
This files are created when you run npm run build.
You can find the file name on webpack.config.js

**Comment by gunnrcrakr** [comment]
> This files are created when you run npm run build.
> You can find the file name on webpack.config.js

After i "npm run-script build"

https://i.imgur.com/2X4tEBd.png

**Comment by moikzz214** [comment]
It is compiling correctly. when you run that it will create src folder and the bundle.css & bundle.js
the filename is based on what you setup on webpack.config.js
