### ISSUE TITLE
How to add new view 

### ISSUE THREAD

**Issue by amrigo** [moikzz214/Codeigniter4_vue_vuetify_webpack_installation#2]
Thank's for this great project, can i ask you some questions ? 
I am trying to add a new view, how can i add a new view, controller and model? 
The Vue instance will be ready to use? or what is the right way ? 
if i need a computed property or a method, where do i need to edit ? only into main.js ?

**Comment by moikzz214** [comment]
Hi. I only use this as a fresh start. As for the project you can check it in here https://github.com/moikzz214/codeigniter-4-vue-vuetify-js-webpack-project

it's more updated and the Vue is ready to use.
